# Generated by Django 5.1.3 on 2024-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('artista', models.CharField(max_length=50)),
                ('duracion', models.DurationField()),
                ('fecha_publicacion', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('discografia', models.CharField(max_length=50)),
            ],
        ),
    ]
