# Generated by Django 5.1.3 on 2024-12-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
                ('genero', models.CharField(max_length=50)),
                ('estreno', models.DateField()),
            ],
        ),
    ]
