# Generated by Django 5.1.4 on 2024-12-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('sinopsis', models.CharField(max_length=500)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
